### ISSUE TITLE
Leetcode Signin Problem

### ISSUE THREAD

**Issue by raman08** [ianding1/leetcode.vim#67]
While signing in I got the following error:

```
Error detected while processing function leetcode#SignIn[1]..<SNR>102_LoadSessionCookie[6]..
provider#python3#Call:
line   18:
Error invoking 'python_eval' on channel 3 (python3-script-host):
error caught in request handler 'python_eval ['leetcode.load_session_cookie("firefox")']':
Traceback (most recent call last):
  File "/home/raman/.local/lib/python3.10/site-packages/secretstorage/util.py", line 46, in
send_and_get_reply
    return self._connection.send_and_get_reply(msg, unwrap=True)
  File "/home/raman/.local/lib/python3.10/site-packages/jeepney/io/blocking.py", line 190, i
n send_and_get_reply
    return unwrap_msg(msg_in)
  File "/home/raman/.local/lib/python3.10/site-packages/jeepney/wrappers.py", line 214, in u
nwrap_msg
    raise DBusErrorResponse(msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownMethod] ('Object does
 not exist at path “/org/freedesktop/secrets/collection/login”',)

```

**Comment by SmartDengC** [comment]
Excuse me ,i have the same problem, have you solved it?

**Comment by Virgilio-AI** [comment]
I also have the same problem arch linux

**Comment by raman08** [comment]
@smartDengC Sorry, I have not been able to solve the problem.

**Comment by papupupu** [comment]
I slove that with https://github.com/python-poetry/poetry/issues/3662#issuecomment-854327667
Also happening here, although I am using conda

I could fix it by following your advice and explictly setting a backend for keyring. So I created the file ~/.config/python_keyring/keyringrc.cfg with the following content:

[backend]
default-keyring=keyring.backends.SecretService.Keyring
Disabling keyring also got rid of the error but then poetry wouldn't authenticate.
