### ISSUE TITLE
Error when loading problems already (or partially) solved on leetcode.com

### ISSUE THREAD

**Issue by julien-me** [ianding1/leetcode.vim#72]
Any time I select a problem that I already solved, or started to solve, on leetcode I get this error:
```
Error detected while processing function <SNR>71_HandleProblemListCR[65]..leetcode#ResetSolution[26]..provider#python3#Call:           
line   18:                                                                                                                             
Error invoking 'python_eval' on channel 4 (python3-script-host):                                                                       
error caught in request handler 'python_eval ['leetcode.get_submission(524855354)']':                                                  
Traceback (most recent call last):                                                                                                     
  File "/home/me/Envs/neovim3/lib/python3.9/site-packages/pynvim/plugin/script_host.py", line 167, in python_eval           
    return eval(expr, self.module.__dict__)                                                                                            
  File "<string>", line 1, in <module>                                                                                                 
  File "/home/me/.config/nvim/plugged/leetcode.vim/autoload/leetcode.py", line 509, in get_submission                              
    'state': _status_to_name(int(_group1(re.search(r"status_code: parseInt\('([^']*)'", s),                                            
ValueError: invalid literal for int() with base 10: 'not found' 
```

I'm using neovim v0.5.0 on Debian Bullseye.

**Comment by user10724** [comment]
I met the same problem.Is it solved?

**Comment by zhoupro** [comment]
https://github.com/zhoupro/leetcode.vim  I solve it this day.  I rewrite this plugin, so no mr.

**Comment by mbledkowski** [comment]
Hi, developer of this extension has not been active on GitHub since 2020. I created repository where I keep maintaining this extension - https://github.com/mbledkowski/neuleetcode.vim. Please submit your issues there.
