### ISSUE TITLE
Cannot signin

### ISSUE THREAD

**Issue by adnanhashmi09** [ianding1/leetcode.vim#76]
I get this error while trying to signin
```
Error detected while processing function leetcode#SignIn[1]..<SNR>32_LoadSessionCookie[6]..provider#python3#Call[18]..<SNR>32_LoadSessionCookie:
line    6:
Please set a password for your new keyring: Warning: Password input may be echoed.
Error detected while processing function leetcode#SignIn[1]..<SNR>32_LoadSessionCookie[6]..provider#python3#Call:
line   18:
Error invoking 'python_eval' on channel 3 (python3-script-host):
error caught in request handler 'python_eval ['leetcode.load_session_cookie("firefox")']':
Traceback (most recent call last):
  File "/usr/lib/python3.11/getpass.py", line 69, in unix_getpass
    old = termios.tcgetattr(fd)     # a copy to save
          ^^^^^^^^^^^^^^^^^^^^^
termios.error: (25, 'Inappropriate ioctl for device')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adnan/.local/lib/python3.11/site-packages/pynvim/plugin/script_host.py", line 167, in python_eval
    return eval(expr, self.module.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/home/adnan/.local/share/lunarvim/site/pack/lazy/opt/leetcode.vim/autoload/leetcode.py", line 179, in load_session_cookie
    keyring.set_password('leetcode.vim', 'SESSION_COOKIE', session_cookie_raw)
  File "/home/adnan/.local/lib/python3.11/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/home/adnan/.local/lib/python3.11/site-packages/keyring/backends/chainer.py", line 56, in set_password
    return keyring.set_password(service, username, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adnan/.local/lib/python3.11/site-packages/keyrings/alt/file_base.py", line 125, in set_password
    password_encrypted = self.encrypt(password.encode('utf-8'), assoc)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adnan/.local/lib/python3.11/site-packages/keyrings/alt/file.py", line 204, in encrypt
    cipher = self._create_cipher(self.keyring_key, salt, IV)
                                 ^^^^^^^^^^^^^^^^
  File "/home/adnan/.local/lib/python3.11/site-packages/jaraco/classes/properties.py", line 32, in __get__
    return self.fget(obj)
           ^^^^^^^^^^^^^^
  File "/home/adnan/.local/lib/python3.11/site-packages/keyrings/alt/file.py", line 102, in keyring_key
    self._init_file()
  File "/home/adnan/.local/lib/python3.11/site-packages/keyrings/alt/file.py", line 109, in _init_file
    self.keyring_key = self._get_new_password()
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adnan/.local/lib/python3.11/site-packages/keyrings/alt/file.py", line 67, in _get_new_password
    password = getpass.getpass("Please set a password for your new keyring: ")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/getpass.py", line 91, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/getpass.py", line 126, in fallback_getpass
    return _raw_input(prompt, stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/getpass.py", line 148, in _raw_input
    raise EOFError
EOFError
```

**Comment by Chaitanya-Shahare** [comment]
This reply might help 

https://github.com/ianding1/leetcode.vim/issues/65#issuecomment-788936319

**Comment by Chaitanya-Shahare** [comment]
let me know if you have figured out a way to run this plugin, I can't seem to get it to work
